# MySQL ?????? ?? ??
jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://127.0.0.1:3306/260617_test_db
jdbc.username=jmg
jdbc.password=jmg

# ??? ? ?? (????)
jdbc.initialSize=5
jdbc.maxActive=10
jdbc.maxIdle=5
jdbc.minIdle=2